routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/vergabebedingungen', 'WelcomeController@termsOfUse')->name('termsOfUse');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('bookings/{booking}/decide/{user}', 'BookingController@decide')->name('bookings.decide');
Route::post('bookings/{booking}/decide/{user}', 'BookingController@storeDecision')->name('bookings.storeDecision');

Route::resource('bookings', 'BookingController');

Route::get('verify/{booking}', 'VerifyBookingController@index')->name('verify.index');
Route::post('verify/{booking}', 'VerifyBookingController@checkCode')->name('verify.checkCode');
Route::get('verify/{booking}/resend', 'VerifyBookingController@resendCode')->name('verify.resendCode');

Route::get('/mailable', function () {
    $user = App\User::find(1);    
    $booking = App\Booking::find(1);

    return new App\Mail\BookingConfirmed($booking);
});

app/Booking.php
<?php

namespace App;

use App\User;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;

class Booking extends Model
{
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['start', 'end', 'handover_date'];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['title'];

    /**
     * Get the room the booking belongs to.
     */
    public function room()
    {
        return $this->belongsTo('App\Room');
    }

    /**
     * Get the room the booking belongs to.
     */
    public function decidedBy()
    {
        return $this->belongsTo('App\User', 'decided_by');
    }

    /**
     * Get the title.
     *
     * @return bool
     */
    public function getTitle() {
        // return $this->room->name . ": " . $this->start->format('H:i') . " - " . $this->end->format('H:i');
        return $this->room->name;        
    }

    /**
     * Return users that are able to decide on the booking based on the room and and the bookers room number.
     * 
     * @return array
     */
    public function getManagers() {
        // Foreign bookings are handled differently
        if ($this->room->house !== $this->getBookerHouse()) {
            $foreignManagers = $this->room->managers('foreign-manager');
            return [
                // Only the foreign managers are allowed to decide on bookings
                'managers' => $foreignManagers,
                // All normal managers are treated as assistant managers
                'assistant-managers' => $this->room->managers()->diff($foreignManagers)->all(),
            ];
        }

        $booking = $this;
        return [
            'managers' => $this->room->managers('manager')
                            ->filter(function ($value, $key) use($booking) {
                                return (
                                    (($value->pivot->range_from <= $booking->tenant_room_number) || is_null($value->pivot->range_from))
                                    &&
                                    (($value->pivot->range_to >= $booking->tenant_room_number) || is_null($value->pivot->range_to))
                                );
                            }),
            'assistant-managers' => $this->room->managers('assistant-manager')
                            ->filter(function ($value, $key) use($booking) {
                                return (
                                    (($value->pivot->range_from <= $booking->tenant_room_number) || is_null($value->pivot->range_from))
                                    &&
                                    (($value->pivot->range_to >= $booking->tenant_room_number) || is_null($value->pivot->range_to))
                                );
                            }),
        ];
    }

    /**
     * Returns the house of the booker based on the bookers room number.
     * 
     * @return String
     */
    private function getBookerHouse() {
        switch(substr($this->tenant_room_number, 0, 1)) {
            case '1':
                return 'Haus 1';
            case '2':
                return 'Haus 2';
            case '3':
                return 'Haus 3';
            case '4':
                return 'Haus 4';
            case '5':
                return 'Haus 5';
            default: 
                return null;
        } 
    }
    
    /**
     * Return authorization hash variables for booking decision.
     * 
     * @param  \App\User  $user
     * @return String
     */
    public function getAuthorizationHashVariables(User $user) {
        return implode("_", [$this->id, $user->id, $user->api_key]);
    }

    /**
     * Return authorization hash for booking decision.
     * 
     * @param  \App\User  $user
     * @return String
     */
    public function getAuthorizationHash(User $user) {
        return Hash::make($this->getAuthorizationHashVariables($user));
    }
}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use App\Booking;
use App\User;
use App\Room;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

use App\Http\Requests\StoreBooking;
use App\Http\Requests\StoreDecision;

use App\Http\Resources\BookingCollection;

use App\Events\UnverifiedBookingCreated;
use App\Events\BookingRequested;
use App\Events\BookingConfirmed;
use App\Events\BookingDeclined;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request  $request)
    {
        return new BookingCollection(
            Booking::where([
                ['status', 'confirmed'],
                ['start', '>=', $request->input('start', Carbon::now())],
                ['end', '<=', $request->input('end', Carbon::now())]
            ])->get()
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('booking.create', [
            'rooms' => Room::orderBy('house', 'asc')->orderBy('name', 'asc')->get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreBooking  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBooking $request)
    {
        // Create new Booking
        $booking = new Booking;

        // Associate the Room
        $booking->room()->associate($request->input('room'));

        // Format start and end
        $booking->start = Carbon::createFromFormat(
            'Y-m-d H:i', 
            $request->input('date') . ' ' . $request->input('start_time'), 
            'Europe/Berlin'
        );

        $booking->end = Carbon::createFromFormat(
            'Y-m-d H:i', 
            $request->input('date') . ' ' . $request->input('end_time'), 
            'Europe/Berlin'
        );

        // Add a day to end if start time is greater than or equal with end time
        if ($booking->start->gte($booking->end)) {
            $booking->end = $booking->end->addDay();
        }

        // Check if the room is occupied at the desired booking time
        if ($booking->room->occupied($booking->start, $booking->end)) {
            // Redirect with flash message
            return back()
                    ->withInput()
                    ->with('occupied', 'Für den gewünschten Zeitraum ist bereits eine Buchung eingetragen!');
        }

        // Set name
        $booking->tenant_name = $request->input('name');

        // Set email
        $booking->tenant_email = $request->input('email');

        // Set ip address
        $booking->tenant_ip_address = $request->ip();

        // Format and set phone number
        // @TODO: Write a setter for this
        $booking->tenant_phone = phone(
            $request->input('phone'),
            ['AUTO', 'DE'],
            \libphonenumber\PhoneNumberFormat::INTERNATIONAL
        );

        // Set room number
        $booking->tenant_room_number = $request->input('room_number');

        // Set message if filled
        if ($request->filled('message')) $booking->tenant_message = $request->input('message');

        // Save to DB
        $booking->save();

        // Check if a verification is required
        // Verification is required if there are no verified bookings with this email address
        if (Booking::where([
            ['tenant_phone', '=', $booking->tenant_phone],
            ['status', '!=', 'notverified']
        ])->exists()) {
            $booking->status = 'unconfirmed';
            $booking->save();

            // Trigger Event
            event(new BookingRequested($booking));

            // Redirect
            return redirect()->route('bookings.show', [
                'booking' => $booking,
            ]);
        } else {
            // Trigger Event
            // @TODO: Make Event Async
            event(new UnverifiedBookingCreated($booking));

            // Redirect
            return redirect()->route('verify.index', [
                'booking' => $booking,
                'hash' => Hash::make($booking->tenant_email . "-JHH-" . $booking->tenant_phone)
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking)
    {
        switch ($booking->status) {
            case 'unconfirmed':
                return view('booking.unconfirmed');
            case 'confirmed':
                return view('booking.confirmed');
            case 'declined':
                return view('booking.declined');
        }
    }

    /**
     * Show the form for deciding on the specified resource.
     * 
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Booking  $booking
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
    */
    public function decide(Request $request, Booking $booking, User $user) {
        // Verify hash && authorize request
        if(
            !Hash::check($booking->getAuthorizationHashVariables($user), $request->input('hash', null))
            OR !$user->can('decide', $booking)
        ) {
            abort(403, 'Unauthorized action.');
        }

        return view('booking.decide', [
            'booking' => $booking,
            'user' => $user,
        ]);
    }

    /**
     * Store the decision for the specified resource
     *
     * @param  \App\Http\Requests\StoreDecision  $request
     * @param  \App\Booking  $booking
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function storeDecision(StoreDecision $request, Booking $booking, User $user)
    {
        // Verify hash && authorize request
        if(
            !Hash::check($booking->getAuthorizationHashVariables($user), $request->input('hash', null))
            OR !$user->can('decide', $booking)
        ) {
            abort(403, 'Unauthorized action.');
        }

        // Associate user who made the decision with the booking
        $booking->decidedBy()->associate($user);

        // Change database entry depending on decision
        switch ($request->input('type')) {
            case 'confirm':
                // Check if the room is occupied at the desired booking time
                if ($booking->room->occupied($booking->start, $booking->end)) {
                    // Redirect with flash message
                    return back()
                            ->withInput()
                            ->with('occupied', 'Für den gewünschten Zeitraum ist bereits eine Buchung eingetragen! Du kannst diese Anfrage nur ablehnen.');
                }

                // Update variables
                $booking->status = 'confirmed';
                $booking->handover_type = $request->input('handover');
                $booking->handover_date = Carbon::createFromFormat(
                    'Y-m-d H:i', 
                    $request->input('date') . ' ' . $request->input('time'), 
                    'Europe/Berlin'
                );
                $booking->save();

                // Fire event
                event(new BookingConfirmed($booking));
                break;
            case 'decline':
                // Update variables
                $booking->status = 'declined';
                $booking->reason = $request->input('reason');
                $booking->save();

                // Fire event
                event(new BookingDeclined($booking));                
                break;
        }

        // Redirect
        return redirect()->route('bookings.show', [
            'booking' => $booking,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Booking $booking)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        //
    }
}

resources/views/booking/confirmed.blade.php
@extends('layouts.instant')

@section('content')
<div class="container">
    <div class="py-5 text-center">
        <div class="d-block mx-auto mb-4" style="font-size:7em; color:#28a745">
            <i class="far fa-calendar-check"></i>
        </div>
        <h2>Buchung angenommen.</h2>
        {{-- <p class="lead">
            Der zuständige Stockwerkssprecher wurde informiert.
            <br/>
            <b>Bitte beachte:</b> Die Buchung ist erst nach Bestätigung durch den 
            Stockwerkssprecher gültig.
        </p> --}}

    </div>
</div>
@endsection

resources/views/booking/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row mb-md-5 bg-dark text-white">
    <div class="col-md-9 p-3 p-md-5 my-md-3 mx-md-auto">
        <h1 class="display-4">Buchungsanfrage</h1>
    </div>
    <div class="col-md-2 p-0 m-auto offset-md-1"></div>
</div>

<div class="container mb-md-5">

    <!-- Error Messages -->
    @include('shared.errors')

    @if ($message = Session::get('occupied'))
        <div class="alert alert-danger" role="alert">
            {{ $message }}
        </div>
    @endif
    
    <!-- Form -->
    <form method="POST" action="{{ route('bookings.store') }}">

        <!-- CSRF token -->
        {{ csrf_field() }}   

        <!-- Type -->
        <div class="form-group row">
            <label for="selectRoom" class="col-sm-2 col-form-label">
                Raum
            </label>
            <div class="col-sm-10">
                <select class="form-control" id="selectRoom" name="room" aria-describedby="selectRoomHelpBlock">
                    @foreach ($rooms as $room)
                        <option 
                            value="{{ $room->id }}"
                            @if(isset($b) AND $b->type() !== null AND $b->type->id == $room->id) selected @endif>
                                {{ $room->house }} - {{ $room->name }} ({{ $room->floor }})
                        </option>
                    @endforeach
                </select>
                <small id="selectRoomHelpBlock" class="form-text text-muted">
                    Im Normalfall solltest du einen Eckraum aus deinem Haus anmieten.
                </small>
            </div>
        </div>

        <!-- Date and Time -->
        <div class="form-group row">
            <label for="inputDate" class="col-sm-2 col-form-label">
                Datum
            </label>
            <div class="col-sm-4">
                <input 
                    type="date" class="form-control" id="inputDate" name="date"
                    value="{{ old('date', isset($b->date) ? $b->date : null) }}" required>
            </div>
            <label for="inputStartTime" class="col-sm-1 col-form-label">
                von
            </label>
            <div class="col-sm-2">
                <input 
                type="time" class="form-control" id="inputStartTime" name="start_time"
                value="{{ old('start_time', isset($b->start_time) ? $b->start_time : null) }}" required>
            </div>
            <label for="inputEndTime" class="col-sm-1 col-form-label">
                bis
            </label>
            <div class="col-sm-2">
                <input 
                type="time" class="form-control" id="inputEndTime" name="end_time"
                value="{{ old('end_time', isset($b->end_time) ? $b->end_time : null) }}" required>
            </div>
        </div>

        <!-- Name -->
        <div class="form-group row">
            <label for="inputName" class="col-sm-2 col-form-label">
                Name
            </label>
            <div class="col-sm-10">
                <input 
                    type="text" class="form-control" id="inputName" name="name"
                    value="{{ old('name', isset($b->name) ? $b->name : null) }}"
                    placeholder="Max Mustermann" required>
            </div>
        </div>

        <!-- E-Mail -->
        <div class="form-group row">
            <label for="inputEmail" class="col-sm-2 col-form-label">
                E-Mail
            </label>
            <div class="col-sm-10">
                <input 
                    type="email" class="form-control" id="inputEmail" name="email"
                    value="{{ old('email', isset($b->email) ? $b->email : null) }}"
                    placeholder="mail@example.org" required>
            </div>
        </div>

        <!-- Phone -->
        <div class="form-group row">
            <label for="inputPhone" class="col-sm-2 col-form-label">
                Handynummer
            </label>
            <div class="col-sm-10">
                <input 
                    type="tel" class="form-control" id="inputPhone" name="phone"
                    value="{{ old('phone', isset($b->phone) ? $b->phone : null) }}"
                    placeholder="+49 176 123123123" required>
            </div>
        </div>

        <!-- Room Number -->
        <div class="form-group row">
            <label for="inputRoomNumber" class="col-sm-2 col-form-label">
                Zimmer-Nr.
            </label>
            <div class="col-sm-10">
                <input 
                    type="number" class="form-control" id="inputRoomNumber" name="room_number"
                    value="{{ old('room_number', isset($b->room_number) ? $b->room_number : null) }}"
                    placeholder="2002" min="1001" max="5499" required>
            </div>
        </div>

        <!-- Message -->
        <div class="form-group row">
            <label for="textareaMessage" class="col-sm-2 col-form-label">
                Nachricht
            </label>
            <div class="col-sm-10">
                <textarea 
                    class="form-control" id="textareaMessage" name="message" 
                    placeholder="(optional) Deine Nachricht ..." 
                    rows="3">{{ old('message', isset($b->message) ? $b->message : '') }}</textarea>
            </div>
        </div>

        <!-- Terms Of Use -->
        <div class="form-group row">
            {{--  <div class="col-sm-2">Mietbedingungen</div>  --}}
            <div class="offset-sm-2 col-sm-10">
                <div class="form-check">
                    <input 
                        type="checkbox" class="form-check-input" id="inputCheckboxTermsOfUse"
                        name="terms_of_use" required>
                    <label class="form-check-label" for="inputCheckboxTermsOfUse">
                        Die <a href="{{ route('termsOfUse') }}" target="_blank">Vergabebedingungen</a> habe ich gelesen und akzeptiert
                    </label>
                </div>
            </div>
        </div>

        <!-- Submit -->
        <div class="form-group row">
            <div class="offset-sm-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Anfrage absenden</button>
            </div>
        </div>

    </form>
</div>
@endsection


{{--  <!-- Title -->
<div class="form-group row">
    <label for="inputTitle" class="col-sm-2 col-form-label">
        @lang('study.title_field.label')
    </label>
    <div class="col-sm-10">
        <input 
            type="text" class="form-control" id="inputTitle" name="title"
            value="{{ old('title', isset($b->title) ? $b->title : null) }}"
            placeholder="@lang('study.title_field.placeholder')" required>
    </div>
</div>  --}}

resources/views/booking/decide.blade.php
@extends('layouts.instant')

@section('content')
<div class="container">
    <div class="py-5 text-center">
        <div class="d-block mx-auto mb-4" style="font-size:7em; color:#ffc107"> <!-- #6c757d -->
            <i class="fas fa-balance-scale"></i>
        </div>
        <h2>
            Buchungsanfrage von {{ $booking->tenant_name }}
        </h2>
        <h4>
            {{ $booking->room->name }}
        </h4>
        <h5>
            {{ $booking->start->format('l, d.m.Y')}} 
            von {{ $booking->start->format('H:i') }} bis {{ $booking->end->format('H:i') }} Uhr
        </h5>

        <div class="mt-5 row">
            <div class="col-10 mx-auto">
                <!-- Error Messages -->
                @include('shared.errors')
                @if ($message = Session::get('occupied'))
                    <div class="alert alert-danger" role="alert">
                        {{ $message }}
                    </div>
                @endif
                <div class="row">
                    <div class="col-12 col-sm-6 text-left decide-border mb-2 mb-md-0">
                        <!-- Form -->
                        <form method="POST" action="{{ route('bookings.storeDecision', [
                            'booking' => $booking,
                            'user' => $user,
                            'hash' => $booking->getAuthorizationHash($user),
                            'type' => 'confirm',
                        ]) }}">

                            <!-- CSRF token -->
                            {{ csrf_field() }}
                            <div style="min-height: 137px;">
                                <!-- Date and Time -->
                                <div class="form-group">
                                    <label for="inputDate"><b>Termin zur Schlüsselübergabe:</b></label>
                                    <div class="row">
                                        <div class="col-8">
                                            <input type="date" class="form-control" id="inputDate" name="date"
                                            value="{{ old('date', null) }}" required>
                                        </div>
                                        <div class="col-4">
                                            <input type="time" class="form-control" id="inputTime" name="time"
                                            value="{{ old('time', null) }}" required>
                                        </div>
                                    </div>
                                </div>

                                <!-- Type of Handover -->
                                <div class="form-group">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="handover" id="radioInPerson" value="in_person"
                                        @if(old('handover', 'in_person') == 'in_person') checked @endif>
                                        <label class="form-check-label" for="radioInPerson">
                                            Persönliche Übergabe (vor {{ $booking->room->name }})
                                        </label>
                                    </div>

                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="handover" id="radioPostbox" value="postbox"
                                        @if(old('handover') == 'postbox') checked @endif>                                        
                                        <label class="form-check-label" for="radioPostbox">
                                            Schlüsseleinwurf in den Briefkasten ({{ $booking->tenant_room_number }})
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success btn-lg btn-block">Anfrage annehmen</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-12 col-sm-6 text-left">
                        <!-- Form -->
                        <form method="POST" action="{{ route('bookings.storeDecision', [
                            'booking' => $booking,
                            'user' => $user,
                            'hash' => $booking->getAuthorizationHash($user),
                            'type' => 'decline',
                        ]) }}">

                            <!-- CSRF token -->
                            {{ csrf_field() }}

                            <!-- Reason -->
                            <div class="form-group">
                                <label for="textareaReason"><b>Grund:</b></label>
                                <textarea class="form-control" name="reason" id="textareaReason" rows="4" required>{{ old('reason') }}</textarea>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-danger btn-lg btn-block">Anfrage ablehnen</button>
                            </div>
                        </form>
                    </div>                    
                </div>              
            </div>
        </div>

    </div>
</div>
@endsection

resources/views/booking/declined.blade.php
@extends('layouts.instant')

@section('content')
<div class="container">
    <div class="py-5 text-center">
        <div class="d-block mx-auto mb-4" style="font-size:7em; color:#dc3545">
            <i class="far fa-calendar-times"></i>
        </div>
        <h2>Buchung abgelehnt.</h2>
        {{-- <p class="lead">
            Der zuständige Stockwerkssprecher wurde informiert.
            <br/>
            <b>Bitte beachte:</b> Die Buchung ist erst nach Bestätigung durch den 
            Stockwerkssprecher gültig.
        </p> --}}

    </div>
</div>
@endsection

resources/views/booking/unconfirmed.blade.php
@extends('layouts.instant')

@section('content')
<div class="container">
    <div class="py-5 text-center">
        <div class="d-block mx-auto mb-4" style="font-size:7em; color:#17a2b8">
            <i class="far fa-calendar-alt"></i>
        </div>
        <h2>Buchung angefragt!</h2>
        <p class="lead">
            Der zuständige Stockwerkssprecher wurde informiert.
            <br/>
            <b>Bitte beachte:</b> Die Buchung ist erst nach Bestätigung durch den 
            Stockwerkssprecher gültig.
        </p>

    </div>
</div>
@endsection